[package]
name = "happy_feet"
version = "0.1.0"
edition = "2024"
description = "Character movement for the bevy game engine, using avian3d for physics"
license = "MIT OR Apache-2.0"
repository = "https://github.com/atornity/happy_feet"

[features]
default = []
serde = ["dep:serde", "avian3d/serialize"]

[dependencies]
avian3d = "0.6.1"
bevy = { version = "0.18.0", default-features = false }
serde = { version = "1.0.219", optional = true }

[dev-dependencies]
bevy = "0.18.0"
bevy_enhanced_input = "0.21.0"
bevy_skein = "0.5"
